# Generated by Django 5.0.1 on 2024-01-26 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaichat",
            name="logit_bias",
            field=models.ManyToManyField(blank=True, to="api.openailogitbias"),
        ),
        migrations.AlterField(
            model_name="openaichat",
            name="max_tokens",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="openaichat",
            name="presence_penalty",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-2),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="openaichat",
            name="temperature",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="openaichat",
            name="top_p",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
