# Generated by Django 5.0.1 on 2024-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_openaichat_logit_bias_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openaichat",
            name="description",
        ),
        migrations.AddField(
            model_name="openaichat",
            name="identifier",
            field=models.CharField(default="hero", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
