# Generated by Django 5.0.1 on 2024-01-26 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_openaichat_description_openaichat_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIChatCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="details",
                        to="api.openaichat",
                    ),
                ),
                (
                    "diagnoses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="api.openaichat",
                    ),
                ),
                (
                    "examinations",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="examinations",
                        to="api.openaichat",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "OpenAI Chat Cluster",
            },
        ),
    ]
