# Generated by Django 5.0.1 on 2024-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_openaichatcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaichat',
            name='stream',
            field=models.BooleanField(default=False),
        ),
    ]
